markdown_extensions:
- pymdownx.superfences:
    custom_fences:
    - class: mermaid
      format: !!python/name:pymdownx.superfences.fence_code_format ''
      name: mermaid
- mdx_include:
    base_path: components
nav:
- Home: index.md
- events:
  - Member Application Event: events/member_application_event.md
  - New Fundraiser Event: events/new_fundraiser_event.md
  - New Meeting Event: events/new_meeting_event.md
  - New Mission Event: events/new_mission_event.md
  - New Sarex Event: events/new_sarex_event.md
  - New Training Event: events/new_training_event.md
- forms:
  - Enter Contact Info Form: forms/enter_contact_info_form.md
  - Enter Task Form: forms/enter_task_form.md
  - New Fundraiser Form: forms/new_fundraiser_form.md
  - New Meeting Form: forms/new_meeting_form.md
  - New Mission Form: forms/new_mission_form.md
  - New Sarex Form: forms/new_sarex_form.md
  - New Training Form: forms/new_training_form.md
  - Update Dispatch Form: forms/update_dispatch_form.md
  - Update Rsvp Form: forms/update_rsvp_form.md
- sheets:
  - Contact Info Sheet: sheets/contact_info_sheet.md
  - Event Log Sheet: sheets/event_log_sheet.md
  - Task Log Sheet: sheets/task_log_sheet.md
site_name: PSAR Data
site_url: https://briancohan.com/psar-data/
theme:
  accent: teal
  features:
  - navigation.sections
  name: material
  primary: indigo
